### ISSUE TITLE
Cannot read properties of null error

### ISSUE THREAD

**Issue by chkue2** [janniks/vue-notion#132]
notion pageId : 8c1ab01960b049f6a282dda64a94afc7
check api: https://api.vue-notion.workers.dev/v1/page/8c1ab01960b049f6a282dda64a94afc7

### TypeError: Cannot read properties of null (reading '1')
    at mapChars (esm.js:4821:19)
    at processing (esm.js:4900:16)
    at Object.toASCII (esm.js:4921:16)
    at parseHost (esm.js:5367:28)
    at URLStateMachine.parseHostName (esm.js:5817:18)
    at new URLStateMachine (esm.js:5528:44)
    at module.exports.basicURLParse (esm.js:6223:15)
    at new URLImpl (esm.js:6278:39)
    at Object.setup (esm.js:6653:17)
    at new URL (esm.js:6491:18)

he response seems to be outputting normally on the API call, but the status drops to null in the mapChars function within esm.js.

**Comment by ricvillagrana** [comment]
Same error here with Vue 3 and Nuxt 2

**Comment by janniks** [comment]
Thanks, I’ll look i to it 🙏🏻

**Comment by mfnash** [comment]
Is there any update ?
